#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"

LIVE_TIMEOUT_SECONDS="${LIVE_TIMEOUT_SECONDS:-90}" \
LIVE_STABILITY_FRAMES="${LIVE_STABILITY_FRAMES:-600}" \
LIVE_STABILITY_MIN_MS="${LIVE_STABILITY_MIN_MS:-6000}" \
LIVE_FULLSCREEN_ENTER="${LIVE_FULLSCREEN_ENTER:-1}" \
LIVE_DISPLAY_CAPTURE="${LIVE_DISPLAY_CAPTURE:-1}" \
LIVE_REQUIRE_WINDOW_CAPTURE="${LIVE_REQUIRE_WINDOW_CAPTURE:-0}" \
LIVE_MIN_DISPLAY_WIDTH="${LIVE_MIN_DISPLAY_WIDTH:-640}" \
LIVE_MIN_DISPLAY_HEIGHT="${LIVE_MIN_DISPLAY_HEIGHT:-400}" \
"$PROJECT_ROOT/engine/graphics/scripts/run_dxmt_d3d11_live_window_smoke.sh" "$@"
