# LANE EXIT5 — журнал
17:11 · старт лайна EXIT5 · слот свободен, свежие прогоны показывают детерминированное раннее событие A (+35с, sp=0x1119cdbf0, [sp-8]=0x1119cdbe8 → stack-addr, pc==lr==fault) во всех 12 прогонах; фатал = segv pc=0 из guest 0x87ef1403714 (Mono-регион, не в loader list) · план: аппаратный watchpoint на слот 0x1119cdbe8, поймать писателя
17:30 · внедрён аппаратный watchpoint (MACRUNNER_HB_WP_ADDR, arm на каждом потоке, trap-intercept с эмуляцией стора, wp-hit дамп writer pc/lr) · ntdll.so пересобран 17:29, маркер в dist-arm64ec-spike ОК · прогон EXIT5WP1 с WP=0x1119cdbe8 (слот события A)
17:50 · EXIT5WP1 упал на boot-флейке rc=66 (load_dll race, MAX=1); слот перехвачен чужой автоматикой (mr-run pid 35028, TMO=3600) · EXIT5WP2 поставлен в очередь с MAX=3, ждёт слот
18:06 · LONG3600 (мой ntdll, try12-config): МЕНЮ +643s, событие A +38.5s (тот же слот 0x1119cdbe8), фатал +702s (host pc=0x18418770c СТАБИЛЕН между прогонами) · мои rc=66 = известный флейк laneA-дефолтов, не WP · запуск EXIT5WP3 через hk-run-try12-config с WP armed
18:10 · wp-патча в kimi-tree НЕ было (жил только в главном дереве) · портирован: signal_arm64.c + thread.c целиком (diff чисто аддитивный, 0 удалений), macrunner_hb.c — хунк image size · ntdll.so пересобран, sha 1f8413c4, маркер macrunner-hb-wp ×4 в ЦЕЛЕВОМ dist-arm64ec-spike ОК · слот свободен · старт EXIT5WP2 WP=0x1119cdbe8 TMO=600 MAX=3
18:16 · WP v1 поймал только легитимные прологи stp x19/x20 [sp,#-48/-64] (pc 0x7ffd07c30f4, 0x7ffd07a71b0 — arm64x ntdll), событие A при WP НЕ воспроизвелось за +279s (14/14 без WP — к +42s) → порча в этих горячих кадрах · WP v2: печать store0/store1 + per-pc suppression + susp-фильтр по указателям рядом со слотом · EXIT5WP4 запущен
18:28 · РАЗЛОМ: host pc фатала 0x18418770c = pacibsp входа _OSAtomicAdd32Barrier (libsystem_platform, shared cache — стабилен); lr=fault=page-aligned stack-addr (…e400) своего потока; WP4 дошёл до МЕНЮ (+526s Restored language) и живёт в окне фатала · событие A при armed WP не воспроизводится (0/2) — порча/гонка именно в loader-кадрах find_dll_file/RtlGetFullPathName_UEx · собран ntdll с fault-bt (host fp-chain + dladdr) для следующего прогона
18:32 · WP4 ПРОЖИЛ 900s до таймаута (меню +526s, exit=5 НЕ случился; LONG3600 без WP умер +702s) — WP-пертурбация гасит и фатал → порча = гонка, чувствительная к микротаймингу, не детерминированная запись · запущен EXIT5BT1 БЕЗ WP на ntdll с host fp-chain fault-bt для поимки вызывающего _OSAtomicAdd32Barrier с битым lr
